server:
  port: 4042

spring:
  datasource:
    url: jdbc:mysql://172.17.0.1/eventuate
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

eventuateLocal:
  kafka:
    bootstrapServers: 172.17.0.1:9092
  cdc:
    dbUserName: root
    dbPassword: rootpassword
  zookeeper:
    connectionString: 172.17.0.1:2181